### ISSUE TITLE
More package dependency issues

### ISSUE THREAD

**Issue by erex** [DistanceDevelopment/dssd#37]
Brand new install of `dssd` this morning, with following result:

```
> library(dssd)
> shapefile.name <- system.file("extdata", "AreaRStrata.shp", package = "dssd")
> region <- make.region(region.name = "study area",
+                       strata.name = c("North", "NW", "West Upper",
+                                       "West Lower", "SW", "South"),
+                       shape = shapefile.name)
Error in st_area.sfc(st_geometry(x, ...)) : 
  package lwgeom required, please install it first
```

**Comment by erex** [comment]
After installing `lwgeom`, back in business, but run into problems creating a coverage grid by specifying number of grid points when units are degrees of lat/long:

```
> cover <- make.coverage(region,
+                        n.grid.points = 500)
Warning: Coordinate reference system detected but no units can be found. Has this shape been projected - shapefiles should be projected on to a flat plane before surveys are designed. 
Warning: The spacing allocated to strata 1 is larger than either one or both of the x / y dimensions of the region. Cannot generate samplers in this strata.
Warning: No samplers generated.
Error in which(sapply(transects, Negate(is.null))) : 
  argument to 'which' is not logical
```

This can be overcome by specifying spacing rather than n.grid.points, however, an inappropriate warning message is produced:

```
cover <- make.coverage(region,
+                        spacing=0.1)
Warning: Both spacing and n.grid.points specified, n.grid.point will be disregarded.
```
This creates a coverage object, but when I tried to generate transects, I realised I was on a fool's errand. 

`survey <- generate.transects(design)` ran for infinite time; while it was doing so, I remembered that  `dssd` can only work with shapefiles in units of meters or kilometers, correct?  Because line.length and truncation need to be specified in units that are not degrees.  So nothing was going to come of the infinite wait.

Is ther a way for `generate.transects` to interrogate the `region` object to know when a stupid mistake like mine, is being made?

**Comment by erex** [comment]
Returning to the original, projected Area R shapefile, I'm able to visualise the gpx file of transects in Google Earth:

```
shapefile.name <- system.file("extdata", "AreaRProjStrata.shp", package = "dssd")
region <- make.region(region.name = "study area",
                      strata.name = c("North", "NW", "West Upper",
                                      "West Lower", "SW", "South"),
                      shape = shapefile.name)
plot(region)
# Make a coverage grid
cover <- make.coverage(region,
                       n.grid.points = 50)
# Define the design
design <- make.design(region = region,
                      transect.type = "line",
                      design = c("systematic", "systematic",
                                 "eszigzag", "systematic",
                                 "systematic", "eszigzagcom"),
                      line.length = 5000*1000, #5000km x 1000m (projection in m)
                      design.angle = c(160, 135, 170, 135, 50, 60),
                      edge.protocol = "minus",
                      truncation = 3000,
                      coverage.grid = cover)

# Create a single set of transects to check
survey <- generate.transects(design)
plot(region, survey, covered.area = TRUE)

latlonproj <-  "+proj=longlat +datum=WGS84 +no_defs"
write.transects(survey,
                dsn = paste0(tempdir(), "/", "transects.gpx"),
                layer = "lines",
                dataset.options = "GPX_USE_EXTENSIONS=yes",
                proj4string = latlonproj)
```
![image](https://user-images.githubusercontent.com/330744/66195772-37a85000-e68f-11e9-89ec-7bb574368bdc.png)

Much of the design is good, but there are some awkward transects in some of the estuaries.  Granted this is complex topology into which to place a design.
![image](https://user-images.githubusercontent.com/330744/66195900-8950da80-e68f-11e9-9d93-f65ecc04c447.png)

**Comment by lenthomas** [comment]
This is cool!  Well done for getting it into Google Earth -- this kind of thing could be really useful as part of a vignette.  
Looking at the awkward transect issue, I think the take-home message to the user is that they need to decide if these complex indentations are part of the survey area or not; if they aren't then cut them out, likely using some kind of GIS interface; if they are then consider putting into a different stratum and surveying separately (like I did for that BC fjords survey with Rob Williams) or live with the fact that there will be short inconvenient segments at times.  
In the future we could add a feature to delete line segments of less than a given length - but this will inevitably cause non-uniform coverage issues and potential bias.

**Comment by LHMarshall** [comment]
Hmm annoying... lwgeom is a suggested package by sf not an imported one... sf seems to do that for a lot of packages... will check out other packages too as there is a long list of suggested packages in sf... wonder which ones dssd needs

**Comment by LHMarshall** [comment]
@erex @lenthomas 

Yeah I had debated the projection stuff... should I force users to project to something with units?

Before you ran into coverage grid issues you should have recevied a warning Eric when you created the survey region? Did this appear on your machine?

```
> library(dssd)
> shapefile.name <- system.file("extdata", "AreaRStrata.shp", package = "dssd")
> region <- make.region(region.name = "study area",
+                       strata.name = c("North", "NW", "West Upper","West Lower", "SW", "South"),
+                       shape = shapefile.name)
Linking to GEOS 3.7.2, GDAL 2.4.2, PROJ 5.2.0
Warning: Coordinate reference system detected but no units can be found. 
Has this shape been projected - shapefiles should be projected on to a flat 
plane before surveys are designed. 
```

**Comment by erex** [comment]
yes, I received a warning created by make.region().

**Comment by LHMarshall** [comment]
Hmm the reason the coverage went really wrong when the number of points was specified was that even though the coordinates are in lat/lon the area calculation somehow calculated the area in m^2!
Hence the calculations of spacing when number of grid points / number of samplers is supplied is too large and results in the errors you saw. 

I do not want to force user to specify units and / or a crs, they may just want to throw in a few simple coordinates. It is not at all obvious to me how to easily differentiate between a geographic coordinate system that has been projected from one that hasn't. I'm not entirely convinced that checking for a units definition is fullproof.

I can expand the warning given by make.region saying that if the user proceeds without projecting then dssd will be unstable and may generate errors?

```
> sf::st_crs(region@region)
Coordinate Reference System:
  EPSG: 4326 
  proj4string: "+proj=longlat +datum=WGS84 +no_defs"
> sf::st_area(region@region)
Units: [m^2]
[1] 4179214594 8185096189 6314538676 8188835019 2654042414 9289041535
```

**Comment by erex** [comment]
Probably a good idea to give more information and cautions.

**Comment by LHMarshall** [comment]
I have changed the message to:

```
Warning: Coordinate reference system detected but no units can be found. Has this 
shape been projected - shapefiles should be projected on to a flat plane before 
surveys are designed. dssd is unstable and may generate errors when working with 
unprojected regions.
```
 is this sufficient?

**Comment by erex** [comment]
yep, might change "should" to "must"?
