### ISSUE TITLE
Minimum coverage for a design of Zero

### ISSUE THREAD

**Issue by erex** [DistanceDevelopment/dssd#39]
How would it be possible for a design to produce a coverage score of zero?  Zero coverage score means that none of the points in the coverage grid are hit by the design, correct?

That's what happens for the Tentsmuir example from the August workshop

```
library(dssd)
library(sf)
shapefile.name <- system.file("extdata", "TentsmuirUnproj.shp", package = "dssd")
sf.shape <- read_sf(shapefile.name)
st_crs(sf.shape)
proj4string <- "+proj=aea +lat_1=56 +lat_2=62 +lat_0=50 +lon_0=-3 +x_0=0
+y_0=0 +ellps=intl +units=m"
projected.shape <- st_transform(sf.shape, crs = proj4string)
region.tm <- make.region(region.name = "Tentsmuir",
strata.name = c("Main Area", "Morton Lochs"),
shape = projected.shape)
# Set up coverage grid
cover.tm <- make.coverage(region.tm, n.grid.points = 1000)
design.tm <- make.design(region = region.tm,
transect.type = "point",
design = "systematic",
samplers = c(25,15),
design.angle = 0,
edge.protocol = "minus",
truncation = 100,
coverage.grid = cover.tm)
tmp <- run.coverage(design = design.tm, reps = 100)
plot(tmp)
tmp
```
Partial result is:

```
    Coverage Score Summary:
    
Minimum coverage score:  0
Maximum coverage score:  0.7
Mean coverage score:  0.07903614
Coverage score sd:  0.1172211
```

**Comment by LHMarshall** [comment]
@erex minimum coverage scores of 0 mean that some coverage grid points were not hit at all by these 100 example surveys. Given the design I do not find that particularly surprising. I am running now with more reps (100 is too few to assess coverage).

![Screenshot 2019-11-29 at 12 25 07](https://user-images.githubusercontent.com/1295691/69869086-ba224a00-12a3-11ea-8bf5-542155d878f9.png)

**Comment by erex** [comment]
I continue to mix in my brain whether these summary statistics are averaged over simulation replicates or over sampling points.  I was thinking the former when I wrote the comment.

**Comment by LHMarshall** [comment]
@erex minimum coverage scores of 0 mean that some coverage grid points were not hit at all by these 100 example surveys. Given the design I do not find that particularly surprising. I am running now with more reps (100 is too few to assess coverage).

![Screenshot 2019-11-29 at 12 25 07](https://user-images.githubusercontent.com/1295691/69869086-ba224a00-12a3-11ea-8bf5-542155d878f9.png)

I ran with 500 reps (1000 is really better though) and this time the minimum coverage was > 0 . The coverage simulation only calculates an approximation of coverage... to have a good approximation you need to generate lots of surveys! Will look into clarifying documentation.

```    Coverage Score Summary:
    
         Main Area Morton Lochs      Total
Minimum 0.01800000    0.3340000 0.01800000
Mean    0.05421429    0.5665600 0.07978044
Median  0.05400000    0.6300000 0.05400000
Maximum 0.09200000    0.7100000 0.71000000
sd      0.01193510    0.1251553 0.11557318
```
