### ISSUE TITLE
Arguments for plot method

### ISSUE THREAD

**Issue by erex** [DistanceDevelopment/dssd#42]
Nothing in help for the plot() function tells the user about arguments, particularly about the existence of the `covered.area` argument

`strata.id` is another argument unveiled in the vignette

**Comment by LHMarshall** [comment]
Eugh... documenting S4 generics not straight forward!

Changing to make arguments explicit rather than contained in ...

Note to access help for plot methods need to use:
```
?`plot,Survey.Design,ANY-method`
?`plot,Region,ANY-method`
...
```

**Comment by LHMarshall** [comment]
Leaving this open incase I can come up with a better way!

**Comment by LHMarshall** [comment]
I have done some more work on the plotting documentation so all arguments are documented. You can also type

?plot(<object.name>)

to access the relevant help
