### ISSUE TITLE
`write.transects` examples

### ISSUE THREAD

**Issue by erex** [DistanceDevelopment/dssd#50]
All files are written to a `tempdir()` that the user cannot find to see what was generated.  How can a user inspect the result of `write.transects()`?

Could you create the file name outside the call to `write.transects` then print the file name string to the console, making it easier to locate the file for examination?

**Comment by LHMarshall** [comment]
Hmm... I was told to do this by CRAN... not sure I want to mess with it 

why can't user just type tempdir() and then navigate to that folder to find them?

**Comment by erex** [comment]
your example code could include the line

```
print(paste0("Your written files can be found in ", tempdir()))
```

remember you're trying to make things clear to the user.

**Comment by LHMarshall** [comment]
These folders are a pain to find even when you have the 'path' so instead I have advised users to change this pathway in the example code. It is an (understandable) CRAN requirement but not really a sensible location to write files to! 

![Screenshot 2019-12-17 at 10 30 21](https://user-images.githubusercontent.com/1295691/70987733-69d72480-20b8-11ea-8320-a23412990135.png)
