### ISSUE TITLE
`run.coverage` documentation

### ISSUE THREAD

**Issue by erex** [DistanceDevelopment/dssd#51]
Documentation only has 3 headings: description, usage, arguments.  Doesn't describe what the function produces nor includes example of use.

**Comment by LHMarshall** [comment]
The description gives a detailed explanation of the coverage scores and design statistics generated. Will point to ?make.design for example code.
![Screenshot 2019-12-17 at 11 55 42](https://user-images.githubusercontent.com/1295691/70993559-2e425780-20c4-11ea-958f-103d38133bda.png)
