### ISSUE TITLE
`get.coverage` documentation 

### ISSUE THREAD

**Issue by erex** [DistanceDevelopment/dssd#52]
could have example code provided

**Comment by LHMarshall** [comment]
So if I am going to add example code here I would either have to run the coverage or load up a design with the coverage already having being run. The former is problematic for runtime on CRAN checks... CRAN has now got more thorough and states that if runtime is too long then you have to comment out using donttest but then add in an example that can be tested so I have to run a pointless coverage test (a really bad example with too few coverage points and hardly any iterations). The latter involves a rather opaque process to the user. Instead I will add useage of this function to the make.design() examples where I already use run.coverage().

**Comment by erex** [comment]
makes sense; then you can cross-reference make.design() to let users know they can find an example use of run.coverage() there
