### ISSUE TITLE
Holdover path in `run.coverage` object

### ISSUE THREAD

**Issue by erex** [DistanceDevelopment/dssd#59]
Performing a simple simulation and computing coverage scores,
- output from `run.coverage`
```
> str(design.properties)
Formal class 'Line.Transect.Design' [package "dssd"] with 14 slots
  ..@ line.length      : num(0) 
  ..@ bounding.shape   : chr "rectangle"
  ..@ region           :Formal class 'Region' [package "dssd"] with 5 slots
  .. .. ..@ region.name: chr "minkes"
  .. .. ..@ strata.name: chr [1:2] "South" "North"
  .. .. ..@ units      : chr "km"
  .. .. ..@ area       : num [1:2] 63832 116016
  .. .. ..@ region     : sf[,6] [2 x 6] (S3: sf/tbl_df/tbl/data.frame)
  .. .. .. ..$ ID      : int [1:2] 1 2
  .. .. .. ..$ AREA    : num [1:2] 0 0
  .. .. .. ..$ LinkID  : int [1:2] 1 2
  .. .. .. ..$ layer   : chr [1:2] "Study_ar" "Study_ar"
  .. .. .. ..$ path    : chr [1:2] "/Users/lhm/Documents/Work/Conferences/WMM 2019/Shapefiles/Study_ar.shp"
```
the `path` seems a hold over from some other project

**Comment by LHMarshall** [comment]
@erex hmm I'm a bit confused on this one. How did you create the region object associated with this design? The region element @region is an sf object which I don't mess with... my guess is that the path is an entry in the attribute table of the shapefile for some reason. Not sure how that happened... given it obv happened on my machine! 

Yup... it appears QGIS inserted that into the attribute table at some point - can't find the exact shapefile referred to here as it's been moved but others in the vicinity have the same issue. Where has this shapefile made it out into the world? I've checked all the ones packaged with dssd and they are all fine. This one was in my workshop I think, anywhere else?

**Comment by erex** [comment]
Lifted the shape file from your March design workshop; North Sea northern and southern strata
