### ISSUE TITLE
Segmented grid design not working on windows machines with GEOS 3.9.0

### ISSUE THREAD

**Issue by LHMarshall** [DistanceDevelopment/dssd#84]
This bug was originally reported in the dsims repo and more details can be found [here](https://github.com/DistanceDevelopment/dsims/issues/35) along with a link to the associated bug report in sf as the issue was traced upstream.

The issue was finally identified as having arisen with the update to GEOS 3.9.0. rgdal has now been updated I think to use 3.9.1 so we are currently awaiting the windows binaries on CRAN to be rebuilt and then the issue should be resolved. This should happen within the next week.

**Comment by LHMarshall** [comment]
This issue has now been resolved. You will need to reinstall the sf R library from CRAN. Then if you run the code 
```
sf::sf_extSoftVersion()
```
you should see that the GEOS version has been updated to 3.9.1

**Comment by lenthomas** [comment]
Just tried and am still getting 3.9.0 so perhaps that build for windows is not ready yet.

**Comment by LHMarshall** [comment]
@lenthomas hmm can you try again please, then try maybe deleting the current sf installation and then re-installing please? All I did was install from CRAN via R studio on my windows machine. However, I had rolled sf back to a previous version of sf I think 0.9.7 possibly? when it relied on GEOS 3.8.2  (and didn't have the bug - as I needed to re-run the bird nest sims) so I was installing on top of that setup... hope that doesn't complicate things! That would be annoying...

**Comment by LHMarshall** [comment]
@lenthomas hmm can you try again please, then try maybe deleting the current sf installation and then re-installing please? All I did was install from CRAN via R studio on my windows machine. However, I had rolled sf back to a previous version of sf I think 0.9.7 possibly? when it relied on GEOS 3.8.2  (and didn't have the bug - as I needed to re-run the bird nest sims) so I was installing on top of that setup... hope that doesn't complicate things! That would be annoying...
