### ISSUE TITLE
Error in x %*% Mat : non-conformable arguments - caused by XYZ polygon shape

### ISSUE THREAD

**Issue by LHMarshall** [DistanceDevelopment/dssd#85]
dssd appears to be having issues rotating the study area

**Comment by LHMarshall** [comment]
This error was due to the fact that the shapefile was an XYZ polygon shape. To fix change the study region shapefile to an XY polygon / multipolygon shapefile. 

I will look into an automatic way of processing these in the future.

**Comment by nadyacaro** [comment]
Dear Laura,
I have installed the 0.3.2 version but:
cover <- make.coverage(region, n.grid.points = 7500)
got this error:
Error in x %*% Mat : non-conformable arguments

I am not sure if it is related to the same as before or if it is a new one. So far I have managed without a problem the previous steps, for example, generating the region.
Thanks

**Comment by LHMarshall** [comment]
@nadyacaro could you please upload the shape file you are using to create the region so I can take a look, or alternatively E-mail me the files at lhm@st-and.ac.uk Thanks!
