### ISSUE TITLE
dssd not on CRAN

### ISSUE THREAD

**Issue by lenthomas** [DistanceDevelopment/dssd#95]
`dssd` package is currently not on CRAN because of #94 

It can, however, be installed from GitHub via the `devtools` package - see in structions on the [dssd Github home page](https://github.com/DistanceDevelopment/dssd)

We are working to resolve this and get `dssd` back up onto CRAN.

**Comment by erex** [comment]
I see `dssd` has returned to CRAN. I had a look at the "multistratum" vignette and saw some odd output. Re-running the vignette .Rmd code on my computer confirmed those messages persist.

![image](https://github.com/DistanceDevelopment/dssd/assets/330744/669996cf-8383-466d-853b-4753d47b2e48)
and
![image](https://github.com/DistanceDevelopment/dssd/assets/330744/a2aca0bb-2431-407d-ba73-9d053302f93d)
and elsewhere

**Comment by erex** [comment]
Similar messages appear when running the case study from the examples.distancesampling.org page (as I think they are essentially the same analysis)

http://examples.distancesampling.org/dssd-multi-strata/MultiStrataVignette-distill.Rmd


![image](https://github.com/DistanceDevelopment/dssd/assets/330744/edd4c3d5-bd42-42fa-ba4f-8e5dc29c1986)

**Comment by LHMarshall** [comment]
I have opened this as a new issue #100
