### ISSUE TITLE
dssd depends on rgdal, but this package is retired

### ISSUE THREAD

**Issue by lakik** [DistanceDevelopment/dssd#97]
recently rgdal is retired which effects the installation of dssd in R. Are you going to fix that somehow? Thank you?

**Comment by erex** [comment]
@lakik Thanks for noting the retirement of `rgdal`. There is a development version of the `dssd` package that has experimentally removed the dependence on `rgdal`. I do not know how much testing this development version has received.

With those words of caution, you could check out this development version:

```
install_github("DistanceDevelopment/dssd", ref="CRAN-1.0.1")
```

**Comment by lakik** [comment]
Great! Thank you it is working! At least for my current purposes.

**Comment by LHMarshall** [comment]
@erex @lakik I have just merged this branch (as it is) into the master branch and published a release. Mac binary installer to be added soon, windows binary installer on that page. 

Users can either download the binary installation files from here:
https://github.com/DistanceDevelopment/dssd/releases/tag/dssd1.0.1-R4.3.1

Or continue to install from the master branch using 
```
  # First, ensure you have a copy of the `devtools` package:
  if (!nzchar(system.file(package = "devtools"))) install.packages("devtools")
  # then install `dssd` from github:
  devtools::install_github("DistanceDevelopment/dssd", build_vignettes = TRUE)
```
